In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [2, 3, 4]
])

In [3]:
B = np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6],
    [3, 4, 5, 6, 7]
])

In [4]:
print("Matrix A:")
print(A)
print("Shape:", A.shape)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 3 4]]
Shape: (4, 3)


In [5]:
print("\nMatrix B:")
print(B)
print("Shape:", B.shape)



Matrix B:
[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]
Shape: (3, 5)


In [6]:
assert A.shape[1] == B.shape[0]
print("Dimensions match!")

Dimensions match!


In [8]:
C = A @ B

print("Matrix C:")
print(C)
print("Shape:", C.shape)

Matrix C:
[[ 14  20  26  32  38]
 [ 32  47  62  77  92]
 [ 50  74  98 122 146]
 [ 20  29  38  47  56]]
Shape: (4, 5)


In [9]:
print("Total sum:", C.sum())

Total sum: 1120


In [10]:
print("Row sums:", C.sum(axis=1))

Row sums: [130 310 490 190]


In [11]:
print("Column sums:", C.sum(axis=0))

Column sums: [116 170 224 278 332]
