# Task A: Matrix Generation

In [1]:
import numpy as np

# Set the NumPy random seed to 42 for reproducibility.
np.random.seed(42)

# Generate Matrix A of shape (4, 3) containing random integers in the range [1, 10].
A = np.random.randint(1, 11, size=(4, 3))

# Generate Matrix B of shape (3, 5) containing random integers in the range [1, 10].
B = np.random.randint(1, 11, size=(3, 5))

# Display both matrices with clear labels along with their .shape attributes.
print("Matrix A:")
print(A)
print(f"Shape of A: {A.shape}\n")

print("Matrix B:")
print(B)
print(f"Shape of B: {B.shape}")

Matrix A:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]
 [ 5  4  8]]
Shape of A: (4, 3)

Matrix B:
[[ 8  3  6  5  2]
 [ 8  6  2  5  1]
 [10  6  9  1 10]]
Shape of B: (3, 5)


# Task B: Dimension Validation & Dot Product

In [2]:
# Programmatically validate that the inner dimensions match using an assertion:
assert A.shape[1] == B.shape[0], "Inner dimensions do not match for matrix multiplication!"

# Compute the matrix product: C = A * B
C = np.dot(A, B)

# Display the resulting matrix C and verify its shape is (4, 5).
print("Matrix C (A dot B):")
print(C)
print(f"Shape of C: {C.shape}")
assert C.shape == (4, 5), "Shape of C is incorrect!"

Matrix C (A dot B):
[[168  93 122  63  98]
 [196 117 134  70 117]
 [160  99 104  58  93]
 [152  87 110  53  94]]
Shape of C: (4, 5)


# Task C: Reductions & Summary Statistics

In [3]:
# Compute and display the total sum of all elements in matrix C:
total_sum = np.sum(C)
print(f"Total sum of all elements in C: {total_sum}\n")

# Compute and display the row-wise sums ( axis=1 ).
row_sums = np.sum(C, axis=1)
print(f"Row-wise sums of C: {row_sums}\n")

# Compute and display the column-wise sums ( axis=0 ).
col_sums = np.sum(C, axis=0)
print(f"Column-wise sums of C: {col_sums}")

Total sum of all elements in C: 2188

Row-wise sums of C: [544 634 514 496]

Column-wise sums of C: [676 396 470 244 402]
